name: Docker Image CI

on:
  push:
    branches: [ "development" ]
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
      - name: get git describe tag
        # only avaible when pushing tags
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: theeye/theeye-gateway
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            #type=raw,value=latest,enable=false
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub 
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_ENV=production
            APP_VERSION=${{ steps.tagName.outputs.tag }}
