name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - 
     name: Build the Docker image
     uses: actions/checkout@v3
    -
     name: Docker meta
     id: meta
     uses: docker/metadata-action@v4
     with:
          images: theeye/theeye-gateway
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=raw,value=latest
          
    - 
     name: Login to DockerHub
     uses: docker/login-action@v2
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    -      
     name: Build image and push to Docker Hub 
     uses: docker/build-push-action@v3
     with:
          # Note: tags has to be all lower-case
          tags: ${{ steps.meta.outputs.tags }}
          # build on feature branches, push only on main branch
          push: true
